apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "cadavre.dispatcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`{{ required "Value domain is required" .Values.dispatcher.domain }}`)
    kind: Rule
    services:
    - name: {{ include "cadavre.dispatcher.fullname" . }}
      kind: Service
      namespace: {{ .Release.Namespace }}
      port: 80
  tls:
    certResolver: {{ required "Value certResolver is required" .Values.dispatcher.certResolver }}
    domains:
      - main: {{ required "Value domain is required" .Values.dispatcher.domain }}
        sans: []