apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cadavre.dispatcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "{{ .Values.dispatcher.domain }}"
      secretName: "{{ include "cadavre.dispatcher.fullname" . }}-tls"
  rules:
    - host: "{{ .Values.dispatcher.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cadavre.dispatcher.fullname" . }}
                port:
                  number: 80