---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: {{ .Release.Namespace}}
spec:
  provider:
    scaleway:
      region: {{ .Values.scaleway.region }}
      projectId: {{ .Values.scaleway.projectId }}
      accessKey:
        secretRef:
          name: scwsm-secret
          key: access-key
      secretKey:
        secretRef:
          name: scwsm-secret
          key: secret-access-key