---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    scaleway:
      region: {{ .Values.scaleway.region}}
      projectId: {{ .Values.scaleway.projectId }}
      accessKey:
        secretRef:
          name: scwsm-secret
          namespace: default
          key: access-key
      secretKey:
        secretRef:
          namespace: default
          name: scwsm-secret
          key: secret-key