{{- range $s := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $s.name }}
spec:
  refreshInterval: {{ $s.refreshInterval }}
  secretStoreRef:
    name: {{ $s.secretStoreRef}}
    kind: ClusterSecretStore
{{ $s.secret | toYaml | indent 2 }}

{{- end }}
