apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  destination:
    name: in-cluster
    namespace: system-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: cloud-cadavre-exquis
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.14.4
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/k8s/charts/system/cert-manager/values.yaml
    - repoURL: https://github.com/418-Error/cloud-cadavre-exquis
      targetRevision: HEAD
      ref: values