apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  destination:
    name: in-cluster
    namespace: system-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: cloud-cadavre-exquis
  sources:
    - chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: 20.8.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/k8s/charts/system/traefik/values.yaml
    - repoURL: https://github.com/418-Error/cloud-cadavre-exquis
      targetRevision: HEAD
      ref: values