apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps-cadavre-exquis
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  destination:
    name: in-cluster
    namespace: cloud-cadavre-exquis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: cloud-cadavre-exquis
  source:
    path: k8s/apps
    repoURL: https://github.com/418-Error/cloud-cadavre-exquis
    targetRevision: implements/helm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  destination:
    name: in-cluster
    namespace: system-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: cloud-cadavre-exquis
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.9.7
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/k8s/system/external-secrets/values.yaml
    - repoURL: https://github.com/418-Error/cloud-cadavre-exquis
      targetRevision: feat/scaleway
      ref: values
