apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud-cadavre-exquis
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Project containing all applications for the cloud-cadavre-exquis
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
    - https://github.com/418-Error/cloud-cadavre-exquis
    - https://charts.external-secrets.io
    - https://helm.traefik.io/traefik
    - https://charts.jetstack.io
