scaleway:
  projectId: "f2b23448-413a-4d36-a571-114588f03132"

dispatcher:
  domain: cadavre.hackthecrous.com

externalSecrets:
  - name: "infrastructure-postgresql-postgres-creds"
    secretStoreRef: secret-store
    refreshInverval: 60s
    secret:
      target:
        name: "infrastructure-postgresql-postgres-creds"
        creationPolicy: Owner
      data:
      - secretKey: password
        remoteRef:
          key: name:db-password-prod
          version: latest_enabled