postgresql:
  credentialsSecret: &postgresqlCredentialsSecret "infrastructure-postgresql-postgres-creds"
  host: &postgresqlCredentialsHost "infrastructure-postgresql-primary"

dispatcher:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-dispatcher
    tag: 1.0-SNAPSHOT
  certResolver: cert-dispatcher

register:
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-register
    tag: 1.0-SNAPSHOT
  postgresql:
    host: 
    credentialsSecretName: "infrastructure-postgresql-postgres-creds"
    databaseName: "rdb"
    username: "postgres_user"

subject:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

verb:
  replica: 3
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

adjective:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

scaleway:
  region: "fr-par"
  projectId: "f2b23448-413a-4d36-a571-114588f03132"