postgresql:
  credentialsSecret: &postgresqlCredentialsSecret "infrastructure-postgresql-postgres-creds"
  host: &postgresqlCredentialsHost "infrastructure-postgresql-primary"

dispatcher:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-dispatcher
    tag: 1.0-SNAPSHOT
  domain: nathael.lab.oomade.com



register:
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-register
    tag: 1.0-SNAPSHOT
  postgresql:
    host: *postgresqlCredentialsHost
    credentialsSecretName: *postgresqlCredentialsSecret
    databaseName: "register"

subject:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

verb:
  replica: 1
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

adjective:
  replica: 2
  image:
    repository: docker.io/fteychene
    name: cloud-cadavre-exquis-provider
    tag: 1.0-SNAPSHOT

externalSecrets:
  - name: "infrastructure-postgresql-postgres-creds"
    secretStoreRef: secret-store
    refreshInverval: 60s
    secret:
      target:
        name: "infrastructure-postgresql-postgres-creds"
        creationPolicy: Owner
      data:
      - secretKey: password
        remoteRef:
          key: id:f640d5de-440a-412f-8805-9eb70469eaf8
          version: latest_enabled

scaleway:
  region: "fr-par"
  projectId: "f2b23448-413a-4d36-a571-114588f03132"